services:
    db:
        build:
            context: docker/mariadb
            args:
                UID: ${USERID}
        volumes:
             - data_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
    php:
        build:
            context: docker/php8.3-fpm
            args:
                TIMEZONE: ${TIMEZONE}
                UID: ${USERID}
        user: ${USERID}
        volumes:
            - ${APP_PATH}:/var/www/projets
            
    web:
        image: caddy:2
        ports:
            - "8000:80"
            - "8443:443"
            - "8443:443/udp"
        volumes:
            - ./docker/caddy:/etc/caddy
            - ${APP_PATH}:/var/www/projets
            - caddy_data:/data
            - caddy_config:/config
            - ./logs/caddy:/var/log/caddy
    mailer:
        image: axllent/mailpit
        ports:
          - 8025:8025
        volumes:
          - data_mailer:/data
        environment:
          MP_MAX_MESSAGES: 5000
          MP_DATA_FILE: /data/mailpit.db
          MP_SMTP_AUTH_ACCEPT_ANY: 1
          MP_SMTP_AUTH_ALLOW_INSECURE: 1
    adminer:
        image: adminer
        ports:
            - 8306:8080
volumes:
    data_mailer:
    caddy_data:
    caddy_config:
    data_db:
